"use client";
import { useEffect, useState } from "react";
import KnowledgeGraph from "./components/KnowledgeGraph";
const NAV = ["Dashboard", "Briefs", "Emails", "Skills", "Research", "Graph", "Settings"];
export default function Home() {
  const [view, setView] = useState("Dashboard");
  const [d, setD] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    fetch("/api/dashboard").then((r) => r.json()).then((data) => { setD(data); setLoading(false); }).catch(() => setLoading(false));
  }, []);
  return (
    <div className="app">
      <aside>
        <div className="brand"><div className="mark">A</div><div><b>Atlas</b><span>Chief of Staff</span></div></div>
        <nav>
          <div className="nav-label">Workspace</div>
          {NAV.map((n) => (<a key={n} className={view === n ? "active" : ""} onClick={() => setView(n)}><i className="ico" />{n}</a>))}
        </nav>
        <div className="side-foot">
          <div className="live"><span className="dot" />{d?.source === "live" ? "Live data" : "Demo mode"}</div>
          <div style={{ marginTop: 6 }}>{d?.founder?.email ?? "atokwales@gmail.com"}</div><div>Winnipeg · CT</div>
        </div>
      </aside>
      <main>
        {loading && <div className="loading">Loading live data…</div>}
        {!loading && view === "Dashboard" && <Dashboard d={d} />}
        {!loading && view === "Briefs" && <Briefs />}
        {!loading && view === "Emails" && <Emails emails={d?.emails ?? []} />}
        {!loading && view === "Skills" && <Skills />}
        {!loading && view === "Research" && <Research />}
        {!loading && view === "Graph" && (<><div className="topline"><div><div className="eyebrow">Knowledge Graph · Supabase</div><h1>Graph</h1><p className="sub">People, companies, events, emails, and deals — rendered live from your data.</p></div></div><div style={{ marginTop: 24 }}><KnowledgeGraph /></div></>)}
        {!loading && view === "Settings" && <Settings d={d} />}
      </main>
    </div>
  );
}
function Dashboard({ d }: { d: any }) {
  const events = d?.events ?? [], risks = d?.risks ?? [], emails = d?.emails ?? [], actions = d?.action_items ?? [];
  return (<>
    <div className="topline"><div><div className="eyebrow">{d?.source === "live" ? "Live · Supabase" : "Demo"}</div><h1>Good morning, <em>{d?.founder?.first_name ?? "Lester"}</em>.</h1><p className="sub">{events.length} events today · {emails.filter((e: any) => e.requires_action).length} email needs action.</p></div></div>
    <div className="grid cols-3">
      <div className="card kpi"><div className="num">{events.length}</div><div className="lab">Events today</div></div>
      <div className="card kpi"><div className="num">{emails.length}</div><div className="lab">Emails triaged</div></div>
      <div className="card kpi"><div className="num">{risks.length}</div><div className="lab">Open risks</div></div>
    </div>
    <div className="grid cols-2">
      <div className="card"><div className="card-head"><div><h2>Risks &amp; flags</h2><div className="meta">Across all modules</div></div><span className="tag live">{risks.length}</span></div>
        {risks.map((r: any, i: number) => (<div className="risk" key={i}><span className={"sev " + r.severity} /><div><span className="cat">{r.category} · {r.severity}</span><p>{r.text}</p></div></div>))}</div>
      <div className="card"><div className="card-head"><div><h2>Action items</h2><div className="meta">Top priorities</div></div><span className="tag live">{actions.length}</span></div>
        {actions.map((a: any, i: number) => (<div className="row" key={i}><span className={"chk" + (a.priority === 1 ? " p1" : "")} /><div className="who"><b>{a.text}</b></div><span className={"due" + (a.due === "Today" ? " today" : "")}>{a.due}</span></div>))}</div>
    </div>
    <div className="card" style={{ marginTop: 18 }}><div className="card-head"><div><h2>Today's schedule</h2><div className="meta">{events.length} blocks · from Calendar</div></div><span className="tag live">Calendar</span></div>
      {events.map((ev: any, i: number) => (<div className="evt" key={i}><div className="t">{new Date(ev.starts_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</div><div className="body"><b>{ev.summary}</b><span>{ev.description}</span></div></div>))}</div>
  </>);
}
function Briefs() { return (<><div className="topline"><div><div className="eyebrow">Morning &amp; Evening</div><h1>Briefs</h1><p className="sub">Generated by Claude. Delivery via Resend — not yet connected.</p></div></div><div className="card" style={{ marginTop: 24 }}><div className="card-head"><div><h2>🌙 Daily Debrief</h2><div className="meta">Pending Fieldy ingestion</div></div><span className="tag stub">Pending</span></div><p className="brief-body">Commitments come from Fieldy transcripts. Once the sync runs, this fills automatically.</p></div></>); }
function Emails({ emails }: { emails: any[] }) {
  const pill = (c: string) => (c === "risk" ? "risk" : c === "product" ? "product" : c === "billing" ? "billing" : "noise");
  return (<><div className="topline"><div><div className="eyebrow">Triage Engine · Gmail</div><h1>Emails</h1><p className="sub">High-signal only, live from your inbox.</p></div></div><div className="card" style={{ marginTop: 24 }}><div className="card-head"><div><h2>Priority inbox</h2><div className="meta">Live</div></div><span className="tag live">{emails.length}</span></div>
    {emails.map((e: any, i: number) => (<div className="row" key={i}><span className={"pill " + pill(e.category)}>{e.category}</span><div className="who"><b>{e.sender}</b><span>{e.subject}</span></div>{e.requires_action && <span className="due today">Action</span>}</div>))}</div></>);
}
function Skills() {
  const mods = [["📅 Calendar Deconflictor","live"],["📬 Email Triage","live"],["🤝 Relationship Ledger","live"],["🎯 Strategic Horizon","live"],["🔴 Risk Monitor","live"],["🧠 Knowledge Graph","live"],["💰 Financial Analyser","stub"],["⚡ Biomarker Optimiser","stub"],["📝 Commitment Extractor","stub"],["🔍 Meeting Researcher","stub"],["🏗️ Schedule Architect","live"]];
  return (<><div className="topline"><div><div className="eyebrow">11 Intelligence Modules</div><h1>Skills</h1><p className="sub">Green = live. Grey = honestly stubbed.</p></div></div><div className="grid cols-3" style={{ marginTop: 24 }}>
    {mods.map(([name, st], i) => (<div className="card" key={i}><h2 style={{ fontSize: 15 }}>{name}</h2><span className={"tag " + st}>{st === "live" ? "Live" : "Not connected"}</span></div>))}</div></>);
}
function Research() { return (<><div className="topline"><div><div className="eyebrow">Meeting Researcher · Firecrawl</div><h1>Research</h1><p className="sub">Background profiles on external attendees.</p></div></div><div className="card" style={{ marginTop: 24 }}><div className="card-head"><div><h2>No external meetings today</h2><div className="meta">Nothing to research</div></div><span className="tag stub">Firecrawl off</span></div><p className="brief-body">When an external meeting appears, this fills with attendee background.</p></div></>); }
function Settings({ d }: { d: any }) {
  return (<><div className="topline"><div><div className="eyebrow">Configuration</div><h1>Settings</h1><p className="sub">Profile and connection status.</p></div></div><div className="grid cols-2" style={{ marginTop: 24 }}>
    <div className="card"><div className="card-head"><div><h2>Profile</h2><div className="meta">{d?.source === "live" ? "Live from DB" : "Demo"}</div></div></div><div className="row"><div className="who"><b>{d?.founder?.first_name ?? "Lester"}</b><span>{d?.founder?.email}</span></div></div><div className="row"><div className="who"><b>Role</b><span>{d?.founder?.role ?? "Operator at Outreach Genius"}</span></div></div></div>
    <div className="card"><div className="card-head"><div><h2>Data source</h2><div className="meta">Honest status</div></div></div><div className="row"><span className={"pill " + (d?.source === "live" ? "product" : "noise")}>{d?.source}</span><div className="who"><b>{d?.source === "live" ? "Supabase connected" : "Demo / no DB creds"}</b><span>Last sync: {d?.last_synced_at ?? "—"}</span></div></div></div></div></>);
}
